version: 0.2
env:
  variables:
    source_ami: 'ami-0af1df87db7b650f4'
phases:
  install:
    commands:
      - echo "Installing packer"
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip && unzip packer.zip
  build:
    commands:
      - ./packer build packer.json
  post_build:
    commands:
      - echo "Build completed `date`"